# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine
WORKDIR /app

# copy project files
COPY package.json tsconfig.json .
COPY .api .api
COPY src src
COPY mcp-config.example.json .
COPY .env.example .

# install dependencies without running scripts
RUN npm install --ignore-scripts

# remove test files to avoid TS errors
RUN rm -rf .api/test .api/tests

# build the project
RUN npm run build

# run the MCP server
ENTRYPOINT ["node", "build/index.js"]
