{
  "openapi": "3.0.3",
  "info": {
    "title": "Lucid Rest API",
    "description": "Lucid Rest API",
    "termsOfService": "https://lucid.co/developer-terms",
    "license": {
      "name": "Lucid",
      "url": "https://lucid.co/developer-terms"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.lucid.co"
    }
  ],
  "tags": [
    {
      "name": "OAuth 2.0 Tokens",
      "description": "OAuth 2.0 Tokens"
    },
    {
      "name": "Accounts",
      "description": "The Account APIs enable the retrieval of information about a Lucid account."
    },
    {
      "name": "Legal Holds",
      "description": "Legal Holds"
    },
    {
      "name": "Documents Collaboration",
      "description": "Documents Collaboration"
    },
    {
      "name": "Folders Collaboration",
      "description": "Folders Collaboration"
    },
    {
      "name": "Document Access",
      "description": "Document Access"
    },
    {
      "name": "Document Embedding",
      "description": "Document Embedding"
    },
    {
      "name": "Folders",
      "description": "Folders"
    },
    {
      "name": "Share Link Security",
      "description": "Share Link Security"
    },
    {
      "name": "Documents Sharing",
      "description": "Documents Sharing"
    },
    {
      "name": "Transfer Content",
      "description": "Transfer Content"
    },
    {
      "name": "Users",
      "description": "Users"
    },
    {
      "name": "Unfurling",
      "description": "Unfurling"
    },
    {
      "name": "Embedding Utils",
      "description": "Embedding Utils"
    },
    {
      "name": "Document Picker",
      "description": "Document Picker"
    },
    {
      "name": "Audit Logs",
      "description": "Audit Logs"
    },
    {
      "name": "Teams",
      "description": "Teams"
    }
  ],
  "paths": {
    "/oauth2/token": {
      "post": {
        "summary": "Create or Refresh Access Token",
        "operationId": "createOrRefreshAccessToken",
        "tags": [
          "OAuth 2.0 Tokens"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/oauth2/token/introspect": {
      "post": {
        "summary": "Introspect Access Token",
        "operationId": "introspectAccessToken",
        "tags": [
          "OAuth 2.0 Tokens"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/oauth2/token/revoke": {
      "post": {
        "summary": "Revoke Access Token",
        "operationId": "revokeAccessToken",
        "tags": [
          "OAuth 2.0 Tokens"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/accounts/me": {
      "get": {
        "summary": "Get Account Information",
        "operationId": "getAccountInformation",
        "tags": [
          "Accounts"
        ],
        "security": [
          {
            "ApiKey": [
              "AccountReadonly"
            ]
          },
          {
            "OAuth2": [
              "account.info"
            ]
          }
        ]
      }
    },
    "/accounts/me/documents/search": {
      "post": {
        "summary": "Search Account Documents",
        "operationId": "SearchAccountDocuments",
        "tags": [
          "Document Access"
        ],
        "security": [
          {
            "ApiKeys": [
              "DocumentAdmin"
            ]
          },
          {
            "Oauth2": [
              "lucidchart.document.content:admin.readonly",
              "lucidspark.document.content:admin.readonly",
              "lucidscale.document.content:admin.readonly"
            ]
          }
        ]
      }
    },
    "/accounts/me/legalHolds": {
      "post": {
        "summary": "Create Legal Hold",
        "operationId": "createLegalHold",
        "tags": [
          "Legal Holds"
        ],
        "security": [
          {
            "ApiKey": [
              "LegalHoldEdit"
            ]
          },
          {
            "OAuth2": [
              "account.legalhold"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get Legal Holds",
        "operationId": "getLegalHolds",
        "tags": [
          "Legal Holds"
        ],
        "security": [
          {
            "ApiKey": [
              "LegalHoldReadonly"
            ]
          },
          {
            "OAuth2": [
              "account.legalhold",
              "account.legalhold:readonly"
            ]
          }
        ]
      }
    },
    "/accounts/me/legalHolds/{legalHoldId}/users/add": {
      "post": {
        "summary": "Add Legal Hold Users",
        "operationId": "addLegalHoldUsers",
        "tags": [
          "Legal Holds"
        ],
        "security": [
          {
            "ApiKey": [
              "LegalHoldEdit"
            ]
          },
          {
            "OAuth2": [
              "account.legalhold",
              "account.legalhold.users"
            ]
          }
        ]
      }
    },
    "/accounts/me/legalHolds/{legalHoldId}/users/remove": {
      "post": {
        "summary": "Remove Legal Hold Users",
        "operationId": "removeLegalHoldUsers",
        "tags": [
          "Legal Holds"
        ],
        "security": [
          {
            "ApiKey": [
              "LegalHoldEdit"
            ]
          },
          {
            "OAuth2": [
              "account.legalhold",
              "account.legalhold.users"
            ]
          }
        ]
      }
    },
    "/accounts/me/legalHolds/{legalHoldId}": {
      "patch": {
        "summary": "Edit Legal Hold",
        "operationId": "editLegalHold",
        "tags": [
          "Legal Holds"
        ],
        "security": [
          {
            "ApiKey": [
              "LegalHoldEdit"
            ]
          },
          {
            "OAuth2": [
              "account.legalhold"
            ]
          }
        ]
      }
    },
    "/accounts/me/legalHolds/{legalHoldId}/release": {
      "post": {
        "summary": "Release Legal Hold",
        "operationId": "releaseLegalHold",
        "tags": [
          "Legal Holds"
        ],
        "security": [
          {
            "ApiKey": [
              "LegalHoldEdit"
            ]
          },
          {
            "OAuth2": [
              "account.legalhold"
            ]
          }
        ]
      }
    },
    "/accounts/me/legalHolds/{legalHoldId}/users": {
      "get": {
        "summary": "Get Legal Hold Users",
        "operationId": "getLegalHoldUsers",
        "tags": [
          "Legal Holds"
        ],
        "security": [
          {
            "ApiKey": [
              "LegalHoldReadonly"
            ]
          },
          {
            "OAuth2": [
              "account.legalhold",
              "account.legalhold:readonly",
              "account.legalhold.users",
              "account.legalhold.users:readonly"
            ]
          }
        ]
      }
    },
    "/accounts/me/legalHoldDocuments/{legalHoldId}": {
      "get": {
        "summary": "Get Legal Hold Documents",
        "operationId": "getLegalHoldDocuments",
        "tags": [
          "Legal Holds"
        ],
        "security": [
          {
            "ApiKey": [
              "LegalHoldReadonly"
            ]
          },
          {
            "OAuth2": [
              "account.legalhold",
              "account.legalhold:readonly"
            ]
          }
        ]
      }
    },
    "/documents/{id}/shares/users/{userId}": {
      "get": {
        "summary": "Get Document User Collaborator",
        "operationId": "getDocumentUserCollaborators",
        "tags": [
          "Documents Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentReadonly"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.content.share.collaborator:readonly",
              "lucidchart.document.app.picker.share.collaborator:readonly",
              "lucidchart.document.app.folder",
              "lucidscale.document.content.share.collaborator:readonly",
              "lucidscale.document.app.picker.share.collaborator:readonly",
              "lucidscale.document.app.folder",
              "lucidspark.document.content.share.collaborator:readonly",
              "lucidspark.document.app.picker.share.collaborator:readonly",
              "lucidspark.document.app.folder"
            ]
          }
        ]
      },
      "put": {
        "summary": "Create/Update Document User Collaborator",
        "operationId": "putDocumentUserCollaborators",
        "tags": [
          "Documents Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentEdit"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.content.share.collaborator",
              "lucidchart.document.app.picker.share.collaborator",
              "lucidchart.document.app.folder",
              "lucidscale.document.content.share.collaborator",
              "lucidscale.document.app.picker.share.collaborator",
              "lucidscale.document.app.folder",
              "lucidspark.document.content.share.collaborator",
              "lucidspark.document.app.picker.share.collaborator",
              "lucidspark.document.app.folder"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Document User Collaborator",
        "operationId": "deleteDocumentUserCollaborators",
        "tags": [
          "Documents Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentEdit"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.content.share.collaborator",
              "lucidchart.document.app.picker.share.collaborator",
              "lucidchart.document.app.folder",
              "lucidscale.document.content.share.collaborator",
              "lucidscale.document.app.picker.share.collaborator",
              "lucidscale.document.app.folder",
              "lucidspark.document.content.share.collaborator",
              "lucidspark.document.app.picker.share.collaborator",
              "lucidspark.document.app.folder"
            ]
          }
        ]
      }
    },
    "/documents/{id}/shares/users": {
      "get": {
        "summary": "List Document User Collaborators",
        "operationId": "listDocumentUserCollaborators",
        "tags": [
          "Documents Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentReadonly"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.content.share.collaborator:readonly",
              "lucidchart.document.app.picker.share.collaborator:readonly",
              "lucidchart.document.app.folder",
              "lucidscale.document.content.share.collaborator:readonly",
              "lucidscale.document.app.picker.share.collaborator:readonly",
              "lucidscale.document.app.folder",
              "lucidspark.document.content.share.collaborator:readonly",
              "lucidspark.document.app.picker.share.collaborator:readonly",
              "lucidspark.document.app.folder"
            ]
          }
        ]
      }
    },
    "/documents/{id}/shares/teams/{teamId}": {
      "get": {
        "summary": "Get Document Team Collaborator",
        "operationId": "getDocumentTeamCollaborator",
        "tags": [
          "Documents Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentReadonly"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.app.folder",
              "lucidchart.document.app.picker.share.collaborator:readonly",
              "lucidchart.document.content.share.collaborator:readonly",
              "lucidscale.document.app.folder",
              "lucidscale.document.app.picker.share.collaborator:readonly",
              "lucidscale.document.content.share.collaborator:readonly",
              "lucidspark.document.app.folder",
              "lucidspark.document.app.picker.share.collaborator:readonly",
              "lucidspark.document.content.share.collaborator:readonly"
            ]
          }
        ]
      },
      "put": {
        "summary": "Create/Update Document Team Collaborator",
        "operationId": "putDocumentTeamCollaborator",
        "tags": [
          "Documents Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentEdit"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.app.folder",
              "lucidchart.document.app.picker.share.collaborator",
              "lucidchart.document.content.share.collaborator",
              "lucidscale.document.app.folder",
              "lucidscale.document.app.picker.share.collaborator",
              "lucidscale.document.content.share.collaborator",
              "lucidspark.document.app.folder",
              "lucidspark.document.app.picker.share.collaborator",
              "lucidspark.document.content.share.collaborator"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Document Team Collaborator",
        "operationId": "deleteDocumentTeamCollaborator",
        "tags": [
          "Documents Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentEdit"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.app.folder",
              "lucidchart.document.app.picker.share.collaborator",
              "lucidchart.document.content.share.collaborator",
              "lucidscale.document.app.folder",
              "lucidscale.document.app.picker.share.collaborator",
              "lucidscale.document.content.share.collaborator",
              "lucidspark.document.app.folder",
              "lucidspark.document.app.picker.share.collaborator",
              "lucidspark.document.content.share.collaborator"
            ]
          }
        ]
      }
    },
    "/folders/{id}/shares/users/{userId}": {
      "get": {
        "summary": "Get Folder User Collaborator",
        "operationId": "getFolderUserCollaborators",
        "tags": [
          "Folders Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderReadonly"
            ]
          },
          {
            "OAuth2": [
              "folder:readonly"
            ]
          }
        ]
      },
      "put": {
        "summary": "Create/Update Folder User Collaborator",
        "operationId": "putFolderUserCollaborator",
        "tags": [
          "Folders Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderEdit"
            ]
          },
          {
            "OAuth2": [
              "folder"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Folder User Collaborator",
        "operationId": "deleteFolderUserCollaborator",
        "tags": [
          "Folders Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderEdit"
            ]
          },
          {
            "OAuth2": [
              "folder"
            ]
          }
        ]
      }
    },
    "/folders/{id}/shares/users": {
      "get": {
        "summary": "List Folder User Collaborators",
        "operationId": "listFolderUserCollaborators",
        "tags": [
          "Folders Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderReadonly"
            ]
          },
          {
            "OAuth2": [
              "folder:readonly"
            ]
          }
        ]
      }
    },
    "/folders/{id}/shares/groups/{groupId}": {
      "get": {
        "summary": "Get Folder Group Collaborator",
        "operationId": "getFolderGroupCollaborator",
        "tags": [
          "Folders Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderReadonly"
            ]
          },
          {
            "OAuth2": [
              "folder",
              "folder:readonly"
            ]
          }
        ]
      },
      "put": {
        "summary": "Create/Update Folder Group Collaborator",
        "operationId": "updateFolderGroupCollaborator",
        "tags": [
          "Folders Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderEdit"
            ]
          },
          {
            "OAuth2": [
              "folder"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Folder Group Collaborator",
        "operationId": "deleteFolderGroupCollaborator",
        "tags": [
          "Folders Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderEdit"
            ]
          },
          {
            "OAuth2": [
              "folder"
            ]
          }
        ]
      }
    },
    "/folders/{id}/shares/groups": {
      "get": {
        "summary": "List Folder Group Collaborators",
        "operationId": "listFolderGroupCollaborators",
        "tags": [
          "Folders Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderReadonly"
            ]
          },
          {
            "OAuth2": [
              "folder",
              "folder:readonly"
            ]
          }
        ]
      }
    },
    "/folders/{id}/shares/teams/{teamId}": {
      "get": {
        "summary": "Get Folder Team Collaborator",
        "operationId": "getFolderTeamCollaborator",
        "tags": [
          "Folders Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderReadonly"
            ]
          },
          {
            "OAuth2": [
              "folder:readonly"
            ]
          }
        ]
      },
      "put": {
        "summary": "Create/Update Folder Team Collaborator",
        "operationId": "putFolderTeamCollaborator",
        "tags": [
          "Folders Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderEdit"
            ]
          },
          {
            "OAuth2": [
              "folder"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Folder Team Collaborator",
        "operationId": "deleteFolderTeamCollaborator",
        "tags": [
          "Folders Collaboration"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderEdit"
            ]
          },
          {
            "OAuth2": [
              "folder"
            ]
          }
        ]
      }
    },
    "/documents": {
      "post": {
        "summary": "Create/Copy/Import Document",
        "operationId": "createOrCopyOrImportDocument",
        "tags": [
          "Document Access"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentEdit"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.content",
              "lucidchart.document.app.folder",
              "lucidspark.document.content",
              "lucidspark.document.app.folder"
            ]
          }
        ]
      }
    },
    "/documents/{id}": {
      "get": {
        "summary": "Get/Export Document",
        "operationId": "getOrExportDocument",
        "tags": [
          "Document Access"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentReadonly"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.content:readonly",
              "lucidchart.document.app.picker:readonly",
              "lucidchart.document.app.folder",
              "lucidscale.document.content:readonly",
              "lucidscale.document.app.picker:readonly",
              "lucidscale.document.app.folder",
              "lucidspark.document.content:readonly",
              "lucidspark.document.app.picker:readonly",
              "lucidspark.document.app.folder"
            ]
          }
        ]
      }
    },
    "/documents/{id}/trash": {
      "post": {
        "summary": "Trash Document",
        "operationId": "trashDocument",
        "tags": [
          "Document Access"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentEdit"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.content",
              "lucidchart.document.app.folder",
              "lucidscale.document.content",
              "lucidscale.document.app.folder",
              "lucidspark.document.content",
              "lucidspark.document.app.folder"
            ]
          }
        ]
      }
    },
    "/documents/search": {
      "post": {
        "summary": "Search Documents",
        "operationId": "searchDocuments",
        "tags": [
          "Document Access"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentReadonly"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.content:readonly",
              "lucidscale.document.content:readonly",
              "lucidspark.document.content:readonly"
            ]
          }
        ]
      }
    },
    "/documents/{id}/contents": {
      "get": {
        "summary": "Document Contents",
        "operationId": "getDocumentContent",
        "tags": [
          "Document Access"
        ],
        "security": [
          {
            "ApiKey": [
              "DocumentReadonly"
            ]
          },
          {
            "OAuth2": [
              "lucidchart.document.content:readonly",
              "lucidchart.document.app.picker:readonly",
              "lucidchart.document.app.folder"
            ]
          }
        ]
      }
    },
    "/embeds": {
      "get": {
        "summary": "Embed Viewer",
        "operationId": "documentEmbeds",
        "tags": [
          "Document Embedding"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/embeds/token": {
      "post": {
        "summary": "Generate Embed Session Token",
        "operationId": "documentEmbedsToken",
        "tags": [
          "Document Embedding"
        ],
        "security": [
          {
            "OAuth2": [
              "lucidchart.document.app.picker.share.embed",
              "lucidscale.document.app.picker.share.embed",
              "lucidspark.document.app.picker.share.embed"
            ]
          }
        ]
      }
    },
    "/folders/{id}": {
      "get": {
        "summary": "Get Folder",
        "operationId": "getFolder",
        "tags": [
          "Folders"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderReadonly"
            ]
          },
          {
            "OAuth2": [
              "folder:readonly"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update Folder",
        "operationId": "updateFolder",
        "tags": [
          "Folders"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderEdit"
            ]
          },
          {
            "OAuth2": [
              "folder"
            ]
          }
        ]
      }
    },
    "/folders": {
      "post": {
        "summary": "Create Folder",
        "operationId": "createFolder",
        "tags": [
          "Folders"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderEdit"
            ]
          },
          {
            "OAuth2": [
              "folder"
            ]
          }
        ]
      }
    },
    "/folders/{id}/trash": {
      "post": {
        "summary": "Trash Folder",
        "operationId": "trashFolder",
        "tags": [
          "Folders"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderEdit"
            ]
          },
          {
            "OAuth2": [
              "folder"
            ]
          }
        ]
      }
    },
    "/folders/{id}/restore": {
      "post": {
        "summary": "Restore Folder",
        "operationId": "restoreFolder",
        "tags": [
          "Folders"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderEdit"
            ]
          },
          {
            "OAuth2": [
              "folder"
            ]
          }
        ]
      }
    },
    "/folders/search": {
      "post": {
        "summary": "Search Folders",
        "operationId": "searchFolders",
        "tags": [
          "Folders"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderReadonly",
              "FolderAdmin"
            ]
          },
          {
            "OAuth2": [
              "folder:readonly",
              "folder:admin.readonly"
            ]
          }
        ]
      }
    },
    "/folders/{id}/contents": {
      "get": {
        "summary": "List Folder Contents",
        "operationId": "listFolderContents",
        "tags": [
          "Folders"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderReadonly"
            ]
          },
          {
            "OAuth2": [
              "folder:readonly"
            ]
          }
        ]
      }
    },
    "/folders/root/contents": {
      "get": {
        "summary": "List Root Folder Contents",
        "operationId": "listRootFolderContents",
        "tags": [
          "Folders"
        ],
        "security": [
          {
            "ApiKey": [
              "FolderReadonly"
            ]
          },
          {
            "OAuth2": [
              "folder:readonly"
            ]
          }
        ]
      }
    },
    "/documents/{id}/shares/shareLinks/{shareLinkId}": {
      "get": {
        "summary": "Get Document Share Link",
        "operationId": "getDocumentShareLink",
        "tags": [
          "Documents Sharing"
        ],
        "security": [
          {
            "OAuth2": [
              "lucidchart.document.content.share.link:readonly",
              "lucidchart.document.app.picker.share.link:readonly",
              "lucidchart.document.app.folder",
              "lucidscale.document.content.share.link:readonly",
              "lucidscale.document.app.picker.share.link:readonly",
              "lucidscale.document.app.folder",
              "lucidspark.document.content.share.link:readonly",
              "lucidspark.document.app.picker.share.link:readonly",
              "lucidspark.document.app.folder"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update Document Share Link",
        "operationId": "updateDocumentShareLink",
        "tags": [
          "Documents Sharing"
        ],
        "security": [
          {
            "OAuth2": [
              "lucidchart.document.content.share.link",
              "lucidchart.document.app.picker.share.link",
              "lucidchart.document.app.folder",
              "lucidscale.document.content.share.link",
              "lucidscale.document.app.picker.share.link",
              "lucidscale.document.app.folder",
              "lucidspark.document.content.share.link",
              "lucidspark.document.app.picker.share.link",
              "lucidspark.document.app.folder"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Document Share Link",
        "operationId": "deleteDocumentShareLink",
        "tags": [
          "Documents Sharing"
        ],
        "security": [
          {
            "OAuth2": [
              "lucidchart.document.content.share.link",
              "lucidchart.document.app.picker.share.link",
              "lucidchart.document.app.folder",
              "lucidscale.document.content.share.link",
              "lucidscale.document.app.picker.share.link",
              "lucidscale.document.app.folder",
              "lucidspark.document.content.share.link",
              "lucidspark.document.app.picker.share.link",
              "lucidspark.document.app.folder"
            ]
          }
        ]
      }
    },
    "/documents/{id}/shares/shareLinks": {
      "post": {
        "summary": "Create Document Share Link",
        "operationId": "createDocumentShareLink",
        "tags": [
          "Documents Sharing"
        ],
        "security": [
          {
            "OAuth2": [
              "lucidchart.document.content.share.link",
              "lucidchart.document.app.picker.share.link",
              "lucidchart.document.app.folder",
              "lucidscale.document.content.share.link",
              "lucidscale.document.app.picker.share.link",
              "lucidscale.document.app.folder",
              "lucidspark.document.content.share.link",
              "lucidspark.document.app.picker.share.link",
              "lucidspark.document.app.folder"
            ]
          }
        ]
      }
    },
    "/shareLink/{shareLinkId}/accept": {
      "post": {
        "summary": "Accept Share Links",
        "operationId": "acceptShareLink",
        "tags": [
          "Sharing"
        ],
        "security": [
          {
            "OAuth2": [
              "invitation.accept"
            ]
          }
        ]
      }
    },
    "/transferUserContent": {
      "post": {
        "summary": "Transfer User Content",
        "operationId": "transferUserContent",
        "tags": [
          "Transfer Content"
        ],
        "security": [
          {
            "OAuth2": [
              "account.user.transfercontent"
            ]
          }
        ],
        "x-rate-limit": {
          "description": "This endpoint has a per account rate limit of 30 requests per 5 seconds."
        }
      }
    },
    "/users/{id}": {
      "get": {
        "summary": "Get User",
        "operationId": "getUser",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "ApiKey": [
              "AccountReadonly"
            ]
          },
          {
            "OAuth2": [
              "account.user:readonly"
            ]
          }
        ]
      }
    },
    "/users": {
      "get": {
        "summary": "List Users",
        "operationId": "listUsers",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": [
              "account.user:readonly"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create User",
        "operationId": "createUser",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": [
              "account.user"
            ]
          }
        ]
      }
    },
    "/users/searchByEmail": {
      "post": {
        "summary": "Search Users By Email",
        "operationId": "userEmailSearch",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "ApiKey": [
              "AccountReadonly"
            ]
          },
          {
            "OAuth2": [
              "account.user:readonly"
            ]
          }
        ]
      }
    },
    "/users/me/profile": {
      "get": {
        "summary": "Get Profile",
        "operationId": "getUserProfile",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "ApiKey": [
              "User"
            ]
          },
          {
            "OAuth2": [
              "user.profile"
            ]
          }
        ]
      }
    },
    "/describeLink": {
      "post": {
        "summary": "Describe Link",
        "operationId": "describeLink",
        "tags": [
          "Unfurling"
        ],
        "security": [
          {
            "ApiKey": []
          },
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/embeds/link": {
      "get": {
        "summary": "Direct Embed",
        "operationId": "directEmbed",
        "tags": [
          "Unfurling"
        ]
      }
    },
    "/documents/{documentId}/embeds/{embedId}": {
      "get": {
        "summary": "Get Document Embed",
        "operationId": "getEmbedInformation",
        "tags": [
          "Embedding Utils"
        ],
        "security": [
          {
            "OAuth2": [
              "lucidchart.document.content.share.embed:readonly",
              "lucidchart.document.app.picker.share.embed:readonly",
              "lucidscale.document.content.share.embed:readonly",
              "lucidscale.document.app.picker.share.embed:readonly",
              "lucidspark.document.content.share.embed:readonly",
              "lucidspark.document.app.picker.share.embed:readonly"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Document Embed",
        "operationId": "deleteEmbed",
        "tags": [
          "Embedding Utils"
        ],
        "security": [
          {
            "OAuth2": [
              "account.info"
            ]
          }
        ]
      }
    },
    "/documents/{documentId}/embeds/{embedId}/document": {
      "get": {
        "summary": "Get Document Embed Document",
        "operationId": "getEmbedDocument",
        "tags": [
          "Embedding Utils"
        ],
        "security": [
          {
            "OAuth2": [
              "lucidchart.document.content.share.embed:readonly",
              "lucidchart.document.app.picker.share.embed:readonly",
              "lucidscale.document.content.share.embed:readonly",
              "lucidscale.document.app.picker.share.embed:readonly",
              "lucidspark.document.content.share.embed:readonly",
              "lucidspark.document.app.picker.share.embed:readonly"
            ]
          }
        ]
      }
    },
    "/documents/{id}/embeds": {
      "post": {
        "summary": "Create Document Embed",
        "operationId": "createEmbed",
        "tags": [
          "Embedding Utils"
        ],
        "security": [
          {
            "OAuth2": [
              "lucidchart.document.content.share.embed",
              "lucidchart.document.app.picker.share.embed",
              "lucidscale.document.content.share.embed",
              "lucidscale.document.app.picker.share.embed",
              "lucidspark.document.content.share.embed",
              "lucidspark.document.app.picker.share.embed"
            ]
          }
        ]
      }
    },
    "/documents/{documentId}/embeds/{embedId}/changeVersion": {
      "post": {
        "summary": "Change Document Embed Version",
        "operationId": "changeEmbedVersion",
        "tags": [
          "Embedding Utils"
        ],
        "security": [
          {
            "OAuth2": [
              "lucidchart.document.content.share.embed",
              "lucidchart.document.app.picker.share.embed",
              "lucidscale.document.content.share.embed",
              "lucidscale.document.app.picker.share.embed",
              "lucidspark.document.content.share.embed",
              "lucidspark.document.app.picker.share.embed"
            ]
          }
        ]
      }
    },
    "/documents/pickerToken": {
      "post": {
        "summary": "Generate Document Picker Token",
        "operationId": "generateDocumentPickerToken",
        "tags": [
          "Document Picker"
        ],
        "security": [
          {
            "OAuth2": [
              "lucidchart.document.app.picker",
              "lucidscale.document.app.picker",
              "lucidspark.document.app.picker"
            ]
          }
        ]
      }
    },
    "/documents/picker?token=:token": {
      "get": {
        "summary": "Embedded Document Picker",
        "operationId": "embeddedDocumentPicker",
        "tags": [
          "Document Picker"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/auditLogs": {
      "get": {
        "summary": "Get Audit Logs",
        "operationId": "getAuditLogs",
        "tags": [
          "Audit Logs"
        ],
        "security": [
          {
            "OAuth2": [
              "account.audit.logs"
            ]
          }
        ]
      }
    },
    "/teams": {
      "get": {
        "summary": "List Teams",
        "operationId": "listTeams",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "ApiKey": [
              "TeamsReadonly",
              "TeamsAdmin"
            ]
          },
          {
            "OAuth2": [
              "teams:readonly",
              "teams:admin"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create Team",
        "operationId": "createTeam",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "ApiKey": [
              "TeamsEdit",
              "TeamsAdmin"
            ]
          },
          {
            "OAuth2": [
              "teams",
              "teams:admin"
            ]
          }
        ]
      }
    },
    "/teams/{id}": {
      "get": {
        "summary": "Get Team",
        "operationId": "getTeam",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "ApiKey": [
              "TeamsReadonly",
              "TeamsAdmin"
            ]
          },
          {
            "OAuth2": [
              "teams:readonly",
              "teams:admin"
            ]
          }
        ]
      }
    },
    "/teams/{id}/users": {
      "get": {
        "summary": "List Users on Team",
        "operationId": "listUsersOnTeam",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "ApiKey": [
              "TeamsReadonly",
              "TeamsAdmin"
            ]
          },
          {
            "OAuth2": [
              "teams:readonly",
              "teams:admin"
            ]
          }
        ]
      }
    },
    "/teams/{id}/users/add": {
      "post": {
        "summary": "Add Users to Team",
        "operationId": "addUsersToTeam",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "ApiKey": [
              "TeamsEdit",
              "TeamsAdmin"
            ]
          },
          {
            "OAuth2": [
              "teams",
              "teams:admin"
            ]
          }
        ]
      }
    },
    "/teams/{id}/users/remove": {
      "post": {
        "summary": "Remove Users from Team",
        "operationId": "removeUsersFromTeam",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "ApiKey": [
              "TeamsEdit",
              "TeamsAdmin"
            ]
          },
          {
            "OAuth2": [
              "teams",
              "teams:admin"
            ]
          }
        ]
      }
    },
    "/teams/{id}/archive": {
      "post": {
        "summary": "Archive Team",
        "operationId": "archiveTeam",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "ApiKey": [
              "TeamsEdit",
              "TeamsAdmin"
            ]
          },
          {
            "OAuth2": [
              "teams",
              "teams:admin"
            ]
          }
        ]
      }
    },
    "/teams/{id}/restore": {
      "post": {
        "summary": "Restore Team",
        "operationId": "restoreTeam",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "ApiKey": [
              "TeamsEdit",
              "TeamsAdmin"
            ]
          },
          {
            "OAuth2": [
              "teams",
              "teams:admin"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://lucid.app/oauth2/authorize",
            "tokenUrl": "https://api.lucid.co/oauth2/token",
            "refreshUrl": "https://api.lucid.co/oauth2/token",
            "scopes": {
              "account.audit.logs": "View audit logs on your account.",
              "account.info": "View basic information about your account (e.g., account ID and account name) .",
              "account.user": "Create, view, edit, and delete users on your account.",
              "account.user:readonly": "View users on your account.",
              "account.user.transfercontent": "Transfer ownership of a user's resources to another user on your account.",
              "folder": "Create, view, edit, share, and delete your folders. Organize your folders and their contents.",
              "folder:readonly": "View any of your folders and list their contents.",
              "invitation.accept": "Accept document and folder share links.",
              "lucidchart.document.app": "View, edit, and manage any Lucidchart document selected for this third-party application. Create, view, edit, and manage any Lucidchart document within its app-specific folder.",
              "lucidchart.document.app.folder": "Create, view, edit, and manage any Lucidchart document within its app-specific folder.",
              "lucidchart.document.app.picker": "View, edit, and manage any Lucidchart document selected for this third-party application.",
              "lucidchart.document.app.picker:readonly": "View and download any Lucidchart document selected for this third-party application.",
              "lucidchart.document.app.picker.share.collaborator": "Create, view, edit, and delete collaborators and invitations of any Lucidchart document on your team or enterprise account selected for the third-party application.",
              "lucidchart.document.app.picker.share.collaborator:readonly": "View collaborators and invitations of any Lucidchart document on your team or enterprise account selected for the third-party application.",
              "lucidchart.document.app.picker.share.embed": "Create, view, edit, and delete embeds of any Lucidchart document on your team or enterprise account selected for the third-party application.",
              "lucidchart.document.app.picker.share.link": "Create, view, edit, and delete the third party application's share links of any Lucidchart document on your team or enterprise account selected for the third-party application.",
              "lucidchart.document.app.picker.share.link:readonly": "View the third party application's share links of any Lucidchart document on your team or enterprise account selected for the third-party application.",
              "lucidchart.document.content": "Create, view, edit, and delete any Lucidchart document on your account.",
              "lucidchart.document.content:readonly": "View and download any Lucidchart document on your account.",
              "lucidchart.document.content.share.collaborator": "Create, view, edit, and delete collaborators and invitations for any of your Lucidchart documents on your team or enterprise account.",
              "lucidchart.document.content.share.collaborator:readonly": "View collaborators and invitations for any of your Lucidchart documents on your team or enterprise account.",
              "lucidchart.document.content.share.embed": "Create, view, edit, and delete embeds for any of your Lucidchart documents on your team or enterprise account.",
              "lucidchart.document.content.share.link": "Create, view, edit, and delete the third party application's share links for any of your Lucidchart documents on your team or enterprise account.",
              "lucidchart.document.content.share.link:readonly": "View the third party application's share links for any of your Lucidchart documents on your team or enterprise account.",
              "lucidscale.document.app": "View, edit, and manage any Lucidscale model selected for this third-party application. Create, view, edit, and manage any Lucidscale model within its app-specific folder.",
              "lucidscale.document.app.folder": "Create, view, edit, and manage any Lucidscale model within its app-specific folder.",
              "lucidscale.document.app.picker": "View, edit, and manage any Lucidscale model selected for this third-party application.",
              "lucidscale.document.app.picker:readonly": "View and download any Lucidscale model selected for this third-party application.",
              "lucidscale.document.app.picker.share.collaborator": "Create, view, edit, and delete collaborators and invitations of any Lucidscale model on your team or enterprise account selected for the third-party application.",
              "lucidscale.document.app.picker.share.collaborator:readonly": "View collaborators and invitations of any Lucidscale model on your team or enterprise account selected for the third-party application.",
              "lucidscale.document.app.picker.share.embed": "Create, view, edit, and delete embeds of any Lucidscale model on your team or enterprise account selected for the third-party application.",
              "lucidscale.document.app.picker.share.link": "Create, view, edit, and delete the third party application's share links of any Lucidscale model on your team or enterprise account selected for the third-party application.",
              "lucidscale.document.app.picker.share.link:readonly": "View the third party application's share links of any Lucidscale model on your team or enterprise account selected for the third-party application.",
              "lucidscale.document.content": "Create, view, edit, and delete any Lucidscale model on your account.",
              "lucidscale.document.content:readonly": "View and download any Lucidscale model on your account.",
              "lucidscale.document.content.share.collaborator": "Create, view, edit, and delete collaborators and invitations for any of your Lucidscale models on your team or enterprise account.",
              "lucidscale.document.content.share.collaborator:readonly": "View collaborators and invitations for any of your Lucidscale models on your team or enterprise account.",
              "lucidscale.document.content.share.embed": "Create, view, edit, and delete embeds for any of your Lucidscale models on your team or enterprise account.",
              "lucidscale.document.content.share.link": "Create, view, edit, and delete the third party application's share links for any of your Lucidscale models on your team or enterprise account.",
              "lucidscale.document.content.share.link:readonly": "View the third party application's share links for any of your Lucidscale models on your team or enterprise account.",
              "lucidspark.document.app": "View, edit, and manage any Lucidspark board selected for this third-party application. Create, view, edit, and manage any Lucidspark board within its app-specific folder.",
              "lucidspark.document.app.folder": "Create, view, edit, and manage any Lucidspark board within its app-specific folder.",
              "lucidspark.document.app.picker": "View, edit, and manage any Lucidspark board selected for this third-party application.",
              "lucidspark.document.app.picker:readonly": "View and download any Lucidspark board selected for this third-party application.",
              "lucidspark.document.app.picker.share.collaborator": "Create, view, edit, and delete collaborators and invitations of any Lucidspark board on your team or enterprise account selected for the third-party application.",
              "lucidspark.document.app.picker.share.collaborator:readonly": "View collaborators and invitations of any Lucidspark board on your team or enterprise account selected for the third-party application.",
              "lucidspark.document.app.picker.share.embed": "Create, view, edit, and delete embeds of any Lucidspark board on your team or enterprise account selected for the third-party application.",
              "lucidspark.document.app.picker.share.link": "Create, view, edit, and delete the third party application's share links of any Lucidspark board on your team or enterprise account selected for the third-party application.",
              "lucidspark.document.app.picker.share.link:readonly": "View the third party application's share links of any Lucidspark board on your team or enterprise account selected for the third-party application.",
              "lucidspark.document.content": "Create, view, edit, and delete any Lucidspark board on your account.",
              "lucidspark.document.content:readonly": "View and download any Lucidspark board on your account.",
              "lucidspark.document.content.share.collaborator": "Create, view, edit, and delete collaborators and invitations for any of your Lucidspark boards on your team or enterprise account.",
              "lucidspark.document.content.share.collaborator:readonly": "View collaborators and invitations for any of your Lucidspark boards on your team or enterprise account.",
              "lucidspark.document.content.share.embed": "Create, view, edit, and delete embeds for any of your Lucidspark boards on your team or enterprise account.",
              "lucidspark.document.content.share.link": "Create, view, edit, and delete the third party application's share links for any of your Lucidspark boards on your team or enterprise account.",
              "lucidspark.document.content.share.link:readonly": "View the third party application's share links for any of your Lucidspark boards on your team or enterprise account.",
              "offline_access": "Continue to perform authorized actions when you’re not logged in (required to refresh tokens).",
              "user.profile": "Allow applications to view basic information about you (e.g., full name, username, and email).",
              "document.app": "View, edit, and manage any Lucidchart document selected for this third-party application. Create, view, edit, and manage any Lucidchart document within its app-specific folder.",
              "document.app.folder": "Create, view, edit, and manage any Lucidchart document within its app-specific folder.",
              "document.app.picker": "View, edit, and manage any Lucidchart document selected for this third-party application.",
              "document.app.picker:readonly": "View and download any Lucidchart document selected for this third-party application.",
              "document.content": "Create, view, edit, and delete any Lucidchart document on your account.",
              "document.content:readonly": "View and download any Lucidchart document on your account.",
              "teams": "Create, view, and edit, archive, and restore any teams on your account. Control which users belong to teams.",
              "teams:readonly": "View any teams on your account and list which users belong to them."
            }
          }
        }
      },
      "ApiKey": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}